services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./:/app:rw,delegated      # your code (hot reload)
      - ./data:/app/data:ro       # CSV read-only to prevent locks
    environment:
      STREAMLIT_SERVER_ADDRESS: "0.0.0.0"
      STREAMLIT_SERVER_PORT: "8501"
      STREAMLIT_SERVER_FILE_WATCHER_TYPE: "poll"
    command: ["streamlit", "run", "app.py"]
